import { useState } from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchBar from "../components/searchBar/searchBar";
import CardsContainer from "../components/cardsContainer/cardsContainer";
import CardModal from "../components/cardModal/cardModal";

export default function Home() {

  const [searchField, setSearchField] = useState("");
  const [individualPokemon, setIndividualPokemon] = useState(null);
  const [showModal, setShowModal] = useState(false);

  const searchPokemon = async () => {
    try {
      const pokemon = await fetch(`https://pokeapi.co/api/v2/pokemon/${searchField}/`);
      const pokemonJSON = await pokemon.json();
      setIndividualPokemon(pokemonJSON);
      setShowModal(true);
    } catch(error) {
      alert("Enter a valid input");
    }
  }

  const capitalizeFirstLetter = (string) => {
    return string.charAt(0).toUpperCase() + string.slice(1);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokecheck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {
          showModal
          &&
          <CardModal 
              closeModal={() => setShowModal(false)} 
              modalState={showModal}
              image={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${individualPokemon.id}.png`}
              pokemonInfo={individualPokemon}
              name={capitalizeFirstLetter(individualPokemon.name)}
          />
        }
        <SearchBar 
          searchContent={searchField} 
          searchFunction={setSearchField}
          searchPokemon={searchPokemon}
        />
        <CardsContainer />
      </main>
    </div>
  )
}
