import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from "react";
import SearchBar from "../components/searchBar/searchBar";

export default function Home() {

  const [counter, setCounter] = useState(0);

  useEffect(() => {
    /*const getPokemons = async () => {
      for(let i=1; i < 21; i++) {
        const pokemon = await fetch(`https://pokeapi.co/api/v2/pokemon/${i}/`);
        const pokemonJSON = await pokemon.json();
        console.log(pokemonJSON);
      }
    };

    getPokemons();*/
    console.log("renderizado");
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokecheck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <SearchBar />
        <div>
          {

          }
        </div>
      </main>
      
    </div>
  )
}
